### ISSUE TITLE
Text is being cut in selection box

### ISSUE THREAD

**Issue by Tanvir-rahman** [utopian-io/utopian.io#13]
#### Expected behavior

Full text should be shown in selection box

#### Actual behavior

It's not fully showing. Ex: "Translation" word

![3a](https://user-images.githubusercontent.com/15964566/32165044-a1938fcc-bd8b-11e7-94f9-e62248298b82.png)

#### How to reproduce

1) Go to [utopian.io](https://utopian.io/)
2) Click on upper selection box

**Comment by azarus** [comment]
@Tanvir-rahman this is an expected behavior, the reason your text is cut is because you have a small screen.

But even thought the mobile view is messed up:

**Current behavior:**
![](https://i.imgur.com/3l1obiO.png)

![](https://i.imgur.com/N8GZpeH.png)

Notice the logo is gone even thought theres enough space to fill.
