### ISSUE TITLE
Utopian.io: Submitting issues to Github must be optional

### ISSUE THREAD

**Issue by propertunist** [utopian-io/utopian.io#31]
*Currently, all issues submitted to Utopian.io are also submitted to Github if the user has already sync'd their Steemit/Utopian account with Github.*

![github](https://tettra.co/wp-content/logos/github.png)

Since some projects do not accept all kinds of issues - such as Steemit/Steem which does not accept 'ideas' except via direct email submission - it is necessary to provide an option when submitting issues to utopian.io to allow the submitter to choose to also submit to Github or not.

A checkbox on the issue submission form should be sufficient to allow the user to choose to optionally submit to Github or not. The checkbox will only be rendered if the user has already sync'd their profile to Github.<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@ura-soul/submitting-issues-to-github-must-be-optional">Utopian.io</a></em><hr/>

**Comment by azarus** [comment]
@propertunist Hi, this is mandatory to submit the issue on github otherwise the project owner wouldn't be notified about the issue. How would it make sense? Not every github project owner knows about utopian.io

Also If they do not accept the issue on github then they will simply close it, you can then resubmit the issue in a different form.
