### ISSUE TITLE
Utopian UI Bug:  Can't Switch Steemit Account

### ISSUE THREAD

**Issue by DoctorLai** [utopian-io/utopian.io#91]
Once user successfully logins to  utopian via steemconnect, he/she  is clearly remembered in the browser and apparently he/she can't switch to other steemit account via Logout button.

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510790565/omkchaj1afjohivv8gvn.png)

Click the logout and it wil redirect to landing page

![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510790596/thocvpoh9kzzvivinlxf.png)

Click the 'Login' and the previous user becomes immediately logged-in!

This bug can be reproduced in both Chrome and Microsoft Edge browsers.

It doesn't make sense that the user logins automatically after a logout.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@justyy/utopian-ui-bug-can-t-switch-steemit-account">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by mooncryption** [comment]
😞  I'm facing this problem as well, I think there should be a request that logs you out of _steemconnect_ as well, I'll have to ask the SteemConnect devs

**Comment by wehmoen** [comment]
Solved

**Comment by azarus** [comment]
@DoctorLai and @mooncryption hey there, this issue is not on utopian.io but with steem connect.
steemconnect keeps your sessions going so you have to log out on steem connect.

**Heres how to switch accounts:**
- Go to https://v2.steemconnect.com/dashboard
- Click Logout:
![](https://i.imgur.com/IpqMOAh.png)
- Go to utopian.io
- Logout:
![](https://i.imgur.com/XgW8IlX.png)
- Log In:
![](https://i.imgur.com/MlI7iMr.png)
- Login with appropriate steemit account vai SteemConnect

@wehmoen issue can be closed
